# Generated by Django 5.0.2 on 2024-03-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('coverphoto', models.ImageField(upload_to='img/')),
                ('para', models.CharField(max_length=300)),
            ],
        ),
    ]
