# Generated by Django 5.0.2 on 2024-03-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverphoto',
            field=models.ImageField(upload_to='path/to/upload/directory/'),
        ),
    ]
